### ISSUE TITLE
[BUG] "Cannot read property 'includes' of undefined" when deploying dataextensions

### ISSUE THREAD

**Issue by eklopfstein** [Accenture/sfmc-devtools#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to deploy data extensions from one BU to another and getting an error right away.

### Expected Behavior

Data extensions deployed to new BU

### Steps To Reproduce

1. Takes all data extensions from one BU to another
2. Delete all data extensions already in BU you are moving data to
3. Run deploy command
4. See "Cannot read property 'includes' of undefined" error within seconds

### Version

3.1.2

### Environment

- OS: Windows 10
- Node: 14.9
- npm: 8.3.2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
hi @eklopfstein could you please check your /logs/ folder for the corresponding log file when this error happened and upload it here? I'm hoping to find a stack trace in it

**warning:** please do check the content for any hints on client data before uploading it to avoid problems...

**Comment by eklopfstein** [comment]
@JoernBerkefeld 

11:23:22.154 debug: :: mcdev 3.1.2 ::
11:23:22.805 info: mcdev:: Deploy
11:23:22.824 info: ::Deploying [project]/[BU]
11:23:23.495 debug: Extra access found:dfu_configure, journeys_aspr, journeys_delete, package_manager_package, package_manager_deploy, deep_linking_asset_read, deep_linking_asset_write, deep_linking_asset_delete, deep_linking_settings_read, deep_linking_settings_write
11:23:23.543 debug: Creating relevant folders for dataExtension in deploy dir
11:23:23.544 error: mcdev.deploy failed: Cannot read property 'includes' of undefined
11:23:23.544 debug: TypeError: Cannot read property 'includes' of undefined
    at C:\Program Files\nodejs\node_modules\mcdev\lib\Deployer.js:195:69
    at Array.filter (<anonymous>)
    at C:\Program Files\nodejs\node_modules\mcdev\lib\Deployer.js:193:66
    at Array.forEach (<anonymous>)
    at Function.createFolderDefinitions (C:\Program Files\nodejs\node_modules\mcdev\lib\Deployer.js:170:25)
    at Deployer.deploy (C:\Program Files\nodejs\node_modules\mcdev\lib\Deployer.js:69:24)
    at Function._deployBU (C:\Program Files\nodejs\node_modules\mcdev\lib\index.js:469:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.deploy (C:\Program Files\nodejs\node_modules\mcdev\lib\index.js:560:17)
11:23:23.544 info: 
:: Deployed 1 BUs

**Comment by DougMidgley** [comment]
Hey @eklopfstein, finally got a chance to look at this. I could only replicate the same kind of error when i remove the "r__folder_Path" field on the data extension object. Can you provide the metadata which you are trying to deploy and/or confirm if the field r__folder_Path is included?

**Comment by JoernBerkefeld** [comment]
hi @eklopfstein sorry we left this open this long. covid ruined our response times... 
As Doug's research showed -  and I checked as well - the code that's failing has been there since 3.0.0

Could the download be from a pre-public version of the tool? Back then we didn't use that particular custom attribute.

**Could you try downloading the DataExtension again and then doing the deploy with that download?**

We'll keep this open for your reply.

**Comment by eklopfstein** [comment]
There are 2 of us working on this, we are both on mcdev version 3.1.2
After looking through the files we noticed that some of the data extensions are missing the "r__folder_Path" field but not all of them. We were going to reload the BUs and run a retrieve again to see if that would fix it but we are getting the following error whenever we try to do anything now. "unable to get local issuer certificate". We believe this might be an issue with our network and are working to resolve it.
I will get back to you with a status on that tomorrow.

**Comment by DougMidgley** [comment]
Hey @eklopfstein  - So that issue with certificates is something i also saw another client have issues with when using the SF library which lies behind our code. For now that can be resolved "insecurely" by trying 
`npm config set strict-ssl false`

see https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate for details

In our next release, we move to sfmc-sdk which is a lib I am working on, where this issue was no longer faced (it replaces request.js with axios).  This release is on the develop branch if you wanna try it out.

**Comment by JoernBerkefeld** [comment]
closing this one for now. if it happens again, please let us know!
