### ISSUE TITLE
[BUG] validation rule noRootFolder triggered for types that dont make sense

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

list All Subscribers - 23211 / All Subscribers: Root folder not allowed. Current folder: my subscribers

### Expected Behavior

should be excluded:

- list
- automation
- attributeSet
- asset, subtype "webpage"

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

7.4.4

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

This change addresses the issue with retrieving the All Subscribers list and excludes specified metadata types from retrieval. It modifies the List class to handle the All Subscribers list correctly and updates the Retriever class to exclude certain metadata types.

I also created pull request: https://github.com/Accenture/sfmc-devtools/pull/1840


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
