### ISSUE TITLE
[BUG] credentials caching needs to be reset on "login failed" error

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i tried debugging a problem and ended up using 2 vscode windows (with 2 different working directories) with the same credentials. Somehow, that broke the solution and window A ended up with invalid credentials while window B kept working. i needed to call your reset method to flush all credentials to get it working again.

### Expected Behavior

- if "Login failed" error appears, credentials are flushed despite the expiry date stating they should still be valid
- multiple terminals should be able to use the same tokens from the central db

### Version

develop-branch

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by DougMidgley** [comment]
so im putting in some changes to how we cache sessions because it may have been the cause (the same name of the org/bu but different client_id would cause issues). 
in order to really flush on login/auth error we would need to extend all API call methods, which is something i think i would rather avoid right now, but as a compromise, I would propose a command to clear sessions in yarg? this could then be easily called in case of issues.
