### ISSUE TITLE
CreateDeltaPackage fails when retrieving DataExtensions

### ISSUE THREAD

**Issue by RobertZimmermann** [Accenture/sfmc-devtools#4]
When running createDeltaPackage it sometimes causes to crash when it retrieves DataExtensions with fuel-soap.

Log:

info: Retrieving as Template: dataExtension
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Error: Invalid argument for the equals operator. Filter[0] cannot be null or empty.
    at /node_modules/mcdev/lib/metadataTypes/MetadataType.js:532:35
    at FuelSoap.<anonymous> (/node_modules/fuel-soap/lib/fuel-soap.js:131:6)
    at FuelSoap.<anonymous> (/node_modules/fuel-soap/lib/fuel-soap.js:603:5)
    at Parser.<anonymous> (/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:315:20)
    . . . . . . .

**Comment by JoernBerkefeld** [comment]
looks like this only happens when `retrieveAsTemplate` (`rt`) is executed for a non-existing data extension. In the case of createDeltaPkg I would assume that somebody renamed or deleted a DE that was previously committed to git - but then forgot to commit that rename/delete.

Let me try to improve the error handling & log/cli output for this case.

**Comment by JoernBerkefeld** [comment]
it now shows proper error messages when `rt` is run for a name that cannot be found on the server
