### ISSUE TITLE
[BUG] Cannot retrieve type automation

### ISSUE THREAD

**Issue by fabi-hears** [Accenture/sfmc-devtools#45]
**Describe the bug**
Retrieving automations fails and stops all imports after automation.

**To Reproduce**
1. CLI: mcdev retrieve X/Y automation 
2. Output: 
13:54:53 info: Retrieving: automation
13:55:09 error: Connection error. Retrying automation
13:55:25 error: Connection error. Retrying automation
13:55:42 error: Connection error. Retrying automation
13:55:57 error: Connection error. Retrying automation
13:56:12 error: Connection error. Retrying automation
...

Logs:
13:54:53.880 info: Retrieving: automation
13:55:09.585 error: Connection error. Retrying automation
13:55:09.586 debug: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
13:55:25.514 error: Connection error. Retrying automation
13:55:25.516 debug: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
13:55:42.779 error: Connection error. Retrying automation
13:55:42.779 debug: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
13:55:57.985 error: Connection error. Retrying automation
13:55:57.985 debug: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)

**Expected behavior**
Retrieving automation works.

**Screenshots**
na

**Versions:**
- mcdev (mcdev --version): 3.0.1
- npm (npm --version): 6.14.13
- node (node --version): v14.17.1
- Operating system (Windows/Mac): Mac

**Comment by JoernBerkefeld** [comment]
Hi @fabi-hears sorry we overlooked your bug report. is that happening for other types as well?
your setup looks fine but this is a network error. my assumption would be that you have some kind of firewall (potentially a corporate one?) that blocks your network traffic?

The class mentioned in the error is not part of DevTools but rather a central one, I'm assuming from node.js and ECONNRESET happens when something fails with your connection. DevTools tends to simply retry in these situation (forever actually, unless you stop it with CTRL+C) but it cant do much more than that.

**Comment by JoernBerkefeld** [comment]
ive actually been seeing a lot of ECONNRESET errors myself now - but all over the place. at first I was thinking I was throttled but then remembered your ticket. I'm starting to believe they changed how the apis respond :| working on adding some more retries into it in better places
